import {
    // Navigation & UI
    Home, User, Users, Settings, Bell, Menu, X, ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
    ArrowDown, ArrowDownCircle, ArrowDownLeft, ArrowDownRight, ArrowLeft, ArrowLeftCircle,
    ArrowRight, ArrowRightCircle, ArrowUp, ArrowUpCircle, ArrowUpLeft, ArrowUpRight,
    ChevronsDown, ChevronsLeft, ChevronsRight, ChevronsUp, ChevronsUpDown,
    MoreHorizontal, MoreVertical, Sidebar, Layout, Grid, Columns, Rows,
    
    // Files & Folders
    Folder, FolderOpen, FolderPlus, FolderMinus, FolderX, FolderCheck, FolderClock, FolderEdit,
    File, FileText, Files, FilePlus, FileMinus, FileX, FileCheck, FileClock, FileEdit,
    FileImage, FileVideo, FileAudio, FileSpreadsheet, FileCode,
    
    // Actions & CRUD
    Plus, PlusCircle, PlusSquare, Minus, MinusCircle, MinusSquare, Edit, Edit2, Edit3,
    Trash, Trash2, Save, Copy, Download, Upload, DownloadCloud, UploadCloud,
    Share, Share2, Send, Forward, Reply, ReplyAll, Undo, Undo2, Redo, Redo2,
    
    // Status & Alerts
    Check, CheckCircle, CheckCircle2, CheckSquare, CheckSquare2, XCircle, XSquare,
    AlertCircle, AlertOctagon, AlertTriangle, Info, HelpCircle,
    Loader, Loader2, RefreshCw, RefreshCcw, RotateCw, RotateCcw, Repeat, Repeat1,
    
    // Communication
    Mail, MailOpen, MailPlus, MailMinus, MailX, MailCheck, MessageCircle, MessageSquare,
    Phone, PhoneCall, PhoneForwarded, PhoneIncoming, PhoneMissed, PhoneOff, PhoneOutgoing,
    Mic, MicOff, Video, VideoOff, Camera, CameraOff, Voicemail,
    
    // Media & Entertainment
    Play, PlayCircle, Pause, PauseCircle, StopCircle, SkipBack, SkipForward,
    FastForward, Rewind, Shuffle, Volume, Volume1, Volume2, VolumeX,
    Music, Music2, Music3, Music4, Radio, Headphones, Speaker, Disc, Disc2, Disc3,
    Film, Image, Images, Tv, Tv2, Monitor, MonitorSpeaker, Gamepad, Gamepad2,
    
    // Social & Branding
    Facebook, Instagram, Twitter, Youtube, Linkedin, Github, Gitlab, Slack,
    Twitch, Dribbble, Figma, Chrome,  Codepen,
    
    // Business & Finance
    Briefcase, Building, Building2, Store, ShoppingCart, ShoppingBag, CreditCard,
    DollarSign, Euro, PoundSterling, Bitcoin, Banknote, Receipt, Calculator,
    TrendingUp, TrendingDown, BarChart, BarChart2, BarChart3, BarChart4,
    PieChart, LineChart, Activity,  Target, Award, Trophy, Medal, Crown,
    
    // Time & Calendar
    Calendar, CalendarDays, CalendarX2, Clock, Clock1, Clock2, Clock3, Clock4, Clock5,
    Clock6, Clock7, Clock8, Clock9, Clock10, Clock11, Clock12, AlarmClock, Timer,
    Hourglass, Watch, Sunrise, Sunset, Sun, Moon, MoonIcon, Star, Stars,
    
    // Location & Maps
    Map, MapPin, Navigation, Navigation2, Compass, Globe, Globe2, Locate, LocateFixed,
    LocateOff, Route, RouteOff, Milestone, Signpost, SignpostBig,
    
    // Transportation
    Car, CarFront, CarTaxiFront, Bike,  Truck, Bus, Train, TrainFront,
    Plane, PlaneTakeoff, PlaneLanding, Ship, Anchor, Fuel, ParkingCircle, ParkingSquare,
    
    // Technology & Development
    Code, Code2, Terminal, Cpu, HardDrive, Database, Server, ServerCog, ServerCrash, ServerOff,
    Wifi, WifiOff, Bluetooth, BluetoothConnected, BluetoothOff, Usb, Cable, Plug, PlugZap,
    Router, Smartphone, Tablet, Laptop,  Keyboard, Mouse, MousePointer,
    MousePointer2, MousePointerClick, Webcam, Printer,  Headset,
    
    // Health & Medical
    Heart, HeartPulse, HeartCrack, HeartOff, Thermometer, Pill, Stethoscope,
    Syringe, Bandage, Cross, Shield, ShieldAlert, ShieldCheck, ShieldX,
    
    // Nature & Weather
    Cloud, CloudRain, CloudSnow, CloudLightning, CloudDrizzle, CloudHail, CloudOff,
    Umbrella, Rainbow, Snowflake, Tornado, Wind, Waves, Mountain, MountainSnow, Trees,
    TreePine, TreeDeciduous, Flower, Flower2, Leaf, Fish, Rabbit, Dog, Cat,
    
    // Food & Dining
    UtensilsCrossed, Utensils,  ChefHat, Coffee, Wine, Beer,
    IceCream, IceCream2, Cookie, Cake, CakeSlice, Apple, Cherry, Grape, 
    
    // Home & Living
    Warehouse, Tent, Bed, BedDouble, BedSingle, 
    Sofa, Table, Table2, Lamp, LampCeiling, LampDesk, LampFloor, LampWallDown, LampWallUp,
    Bath, WashingMachine, Refrigerator, Microwave, 
    
    // Tools & Equipment
    Wrench,  Hammer, Drill, Scissors, Ruler, PaintBucket, Paintbrush,
    Brush, Pencil, Pen, PenTool, Eraser, Paperclip, Pin,  Magnet, Lock, Unlock,
    Key, KeyRound, KeySquare, Vault,  Flashlight,  Flame,
    
    // Sports & Recreation
    Dumbbell, Weight,  Volleyball,
     Dice1, Dice2, Dice3, Dice4, Dice5, Dice6, Puzzle,
    
    // Education & Learning
    GraduationCap, School, School2, BookOpen, Book,  Library, Newspaper,
    Bookmark, BookmarkPlus, BookmarkMinus, BookmarkX, BookmarkCheck,
    Lightbulb, LightbulbOff, Brain, Microscope,
    
    // Shapes & Symbols
    Circle, Square, Triangle, Hexagon, Pentagon, Octagon, Diamond, StarHalf,
    Asterisk, Hash, AtSign, Percent, Copyright,  Infinity,
    Equal,  Divide,
    
    // Text & Formatting
    Type, Bold, Italic, Underline, Strikethrough, AlignLeft, AlignCenter, AlignRight,
    AlignJustify, List, ListOrdered, ListX, ListPlus, ListMinus, ListCheck, ListTodo,
    Indent, Outdent, Quote, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6,
    
    // Arrows & Directions
    ArrowBigDown, ArrowBigLeft, ArrowBigRight, ArrowBigUp, ArrowBigUpDash, ArrowBigDownDash,
    ArrowBigLeftDash, ArrowBigRightDash, CornerDownLeft, CornerDownRight, CornerLeftDown,
    CornerLeftUp, CornerRightDown, CornerRightUp, CornerUpLeft, CornerUpRight,
    
    // Miscellaneous
    Zap, ZapOff, Battery, BatteryCharging, BatteryFull, BatteryLow, Signal, SignalHigh,
    SignalLow, SignalMedium, SignalZero, Antenna, Rss, Podcast, Cast,
    Airplay, NfcIcon, QrCode, Barcode, Scan, ScanLine, Focus,
    ZoomIn, ZoomOut, Maximize, Maximize2, Minimize, Minimize2, Move, Move3d,
    MoveHorizontal, MoveVertical, MoveDiagonal, MoveDiagonal2, 
    Rotate3d, FlipHorizontal, FlipHorizontal2, FlipVertical, FlipVertical2, Crop, 
    Layers, Layers2, Layers3, Filter, FilterX, Search, SearchCheck, SearchX,
    Eye, EyeOff, ToggleLeft, ToggleRight,
    Power, PowerOff, LogIn, LogOut, UserPlus, UserMinus, UserCheck, UserX,
    UserCog, UserCircle, UserSquare, UserRound, Users2, UsersRound,
    Contact, Contact2,  IdCard,
    Tag, Tags, Flag, FlagOff,
    BellOff, BellPlus, BellMinus, BellRing, 
    Vibrate, VibrateOff, Unplug, FlashlightOff,
     Bolt, SunDim, SunMedium, SunMoon, SunSnow,
    CloudSun, CloudMoon, Cloudy, 
    LifeBuoy, ShieldOff, LockKeyhole, Fingerprint, ScanFace,
    Glasses, ContactRound, Ear, EarOff, 
    Footprints, Baby, PersonStanding, Accessibility,  Dna, TestTube, TestTube2, Beaker, FlaskConical, FlaskConicalOff, FlaskRound,
    Atom, Orbit,  Rocket, Satellite, Telescope, Ghost,
    Skull, Biohazard, Radiation,  BugOff,
     Worm, Snail, Turtle, Bird, Feather, Egg, EggFried,
    EggOff, Bone, PawPrint, Milk, MilkOff, Beef, Ham, Popcorn, Salad, Sandwich, Soup,
    Pizza, Donut, Croissant, Banana,
    Carrot, 
    
    // Additional missing icons
    Package, Inbox, Clipboard, ClipboardList, AirVent
  } from 'lucide-react';
  
  export const icons = [
    { name: 'Home', icon: Home },
    { name: 'User', icon: User },
   
    { name: 'Settings', icon: Settings },
    { name: 'Bell', icon: Bell },
     { name: 'FileText', icon: FileText },
     { name: 'Building', icon: Building },
          { name: 'Building2', icon: Building2 },


    { name: 'Folder', icon: Folder },
    { name: 'File', icon: File },
    { name: 'ClipboardList', icon: ClipboardList },
    { name: 'List', icon: List },
    { name: 'Calendar', icon: Calendar },
    { name: 'Inbox', icon: Inbox },
    { name: 'LogOut', icon: LogOut },
    { name: 'Trash2', icon: Trash2 },
    { name: 'BarChart', icon: BarChart },
    { name: 'HelpCircle', icon: HelpCircle },
    { name: 'Activity', icon: Activity },
    { name: 'AirVent', icon: AirVent },
    { name: 'Airplay', icon: Airplay },
    { name: 'AlarmClock', icon: AlarmClock },
    { name: 'AlertCircle', icon: AlertCircle },
    { name: 'AlertOctagon', icon: AlertOctagon },
    { name: 'AlertTriangle', icon: AlertTriangle },
    { name: 'AlignCenter', icon: AlignCenter },
    { name: 'AlignJustify', icon: AlignJustify },
    { name: 'AlignLeft', icon: AlignLeft },
    { name: 'AlignRight', icon: AlignRight },
    { name: 'ArrowDown', icon: ArrowDown },
    { name: 'ArrowDownCircle', icon: ArrowDownCircle },
    { name: 'ArrowDownLeft', icon: ArrowDownLeft },
    { name: 'ArrowDownRight', icon: ArrowDownRight },
    { name: 'ArrowLeft', icon: ArrowLeft },
    { name: 'ArrowLeftCircle', icon: ArrowLeftCircle },
    { name: 'ArrowRight', icon: ArrowRight },
    { name: 'ArrowRightCircle', icon: ArrowRightCircle },
    { name: 'ArrowUp', icon: ArrowUp },
    { name: 'ArrowUpCircle', icon: ArrowUpCircle },
    { name: 'ArrowUpLeft', icon: ArrowUpLeft },
    { name: 'ArrowUpRight', icon: ArrowUpRight },
    { name: 'AtSign', icon: AtSign },
    { name: 'Award', icon: Award },
    { name: 'Banknote', icon: Banknote },
    { name: 'BarChart2', icon: BarChart2 },
    { name: 'Battery', icon: Battery },
    { name: 'BatteryCharging', icon: BatteryCharging },
    { name: 'Bluetooth', icon: Bluetooth },
    { name: 'Bold', icon: Bold },
    { name: 'Book', icon: Book },
    { name: 'Bookmark', icon: Bookmark },
    { name: 'Briefcase', icon: Briefcase },
    { name: 'Brush', icon: Brush },
    { name: 'Cake', icon: Cake },
    { name: 'Camera', icon: Camera },
    { name: 'Cast', icon: Cast },
    { name: 'Check', icon: Check },
    { name: 'CheckCircle', icon: CheckCircle },
    { name: 'CheckSquare', icon: CheckSquare },
    { name: 'ChevronDown', icon: ChevronDown },
    { name: 'ChevronLeft', icon: ChevronLeft },
    { name: 'ChevronRight', icon: ChevronRight },
    { name: 'ChevronUp', icon: ChevronUp },
    { name: 'Chrome', icon: Chrome },
    { name: 'Circle', icon: Circle },
    { name: 'Clipboard', icon: Clipboard },
    { name: 'Clock', icon: Clock },
    { name: 'Cloud', icon: Cloud },
    { name: 'CloudDrizzle', icon: CloudDrizzle },
    { name: 'CloudLightning', icon: CloudLightning },
    { name: 'CloudOff', icon: CloudOff },
    { name: 'CloudRain', icon: CloudRain },
    { name: 'CloudSnow', icon: CloudSnow },
    { name: 'Code', icon: Code },
    { name: 'Codepen', icon: Codepen },
    { name: 'Coffee', icon: Coffee },
    { name: 'Columns', icon: Columns },
    { name: 'Compass', icon: Compass },
    { name: 'Contact', icon: Contact },
    { name: 'Copy', icon: Copy },
    { name: 'Copyright', icon: Copyright },
    { name: 'CreditCard', icon: CreditCard },
    { name: 'Crop', icon: Crop },
    { name: 'Database', icon: Database },
    { name: 'Disc', icon: Disc },
    { name: 'Divide', icon: Divide },

    { name: 'DollarSign', icon: DollarSign },
    { name: 'Download', icon: Download },
    { name: 'DownloadCloud', icon: DownloadCloud },
    { name: 'Dribbble', icon: Dribbble },

    { name: 'Edit', icon: Edit },
    { name: 'Edit2', icon: Edit2 },
    { name: 'Edit3', icon: Edit3 },
    { name: 'Eye', icon: Eye },
    { name: 'EyeOff', icon: EyeOff },
    { name: 'Facebook', icon: Facebook },
    { name: 'FastForward', icon: FastForward },
    { name: 'Feather', icon: Feather },
    { name: 'Film', icon: Film },
    { name: 'Filter', icon: Filter },
    { name: 'Flag', icon: Flag },
    { name: 'Flame', icon: Flame },
    { name: 'Flashlight', icon: Flashlight },
    { name: 'FolderMinus', icon: FolderMinus },
    { name: 'FolderPlus', icon: FolderPlus },
   
    { name: 'Github', icon: Github },
    { name: 'Gitlab', icon: Gitlab },
    { name: 'Globe', icon: Globe },
    { name: 'GraduationCap', icon: GraduationCap },
    { name: 'Grid', icon: Grid },
    { name: 'HardDrive', icon: HardDrive },
    { name: 'Hash', icon: Hash },
    { name: 'Headphones', icon: Headphones },
    { name: 'Heart', icon: Heart },
    { name: 'Hexagon', icon: Hexagon },
    { name: 'Image', icon: Image },
    { name: 'Info', icon: Info },
    { name: 'Instagram', icon: Instagram },
    { name: 'Italic', icon: Italic },
    { name: 'Key', icon: Key },
    { name: 'Layers', icon: Layers },
    { name: 'Layout', icon: Layout },
    { name: 'LifeBuoy', icon: LifeBuoy },

    { name: 'Linkedin', icon: Linkedin },
    { name: 'Loader2', icon: Loader2 },
    { name: 'Locate', icon: Locate },
    { name: 'Lock', icon: Lock },
    { name: 'Mail', icon: Mail },
    { name: 'Map', icon: Map },
    { name: 'MapPin', icon: MapPin },
    { name: 'Maximize', icon: Maximize },
    { name: 'Maximize2', icon: Maximize2 },
    { name: 'Menu', icon: Menu },
    { name: 'MessageCircle', icon: MessageCircle },
    { name: 'MessageSquare', icon: MessageSquare },
    { name: 'Mic', icon: Mic },
    { name: 'MicOff', icon: MicOff },
    { name: 'Minimize', icon: Minimize },
    { name: 'Minimize2', icon: Minimize2 },
    { name: 'Minus', icon: Minus },
    { name: 'MinusCircle', icon: MinusCircle },
    { name: 'MinusSquare', icon: MinusSquare },
    { name: 'Monitor', icon: Monitor },
    { name: 'Moon', icon: Moon },
    { name: 'MoreHorizontal', icon: MoreHorizontal },
    { name: 'MoreVertical', icon: MoreVertical },
    { name: 'MousePointer', icon: MousePointer },
    { name: 'Move', icon: Move },
    { name: 'Music', icon: Music },
    { name: 'Navigation', icon: Navigation },
    { name: 'Navigation2', icon: Navigation2 },
    { name: 'Octagon', icon: Octagon },
    { name: 'Package', icon: Package },
    { name: 'Paperclip', icon: Paperclip },
    { name: 'Pause', icon: Pause },
    { name: 'PauseCircle', icon: PauseCircle },
    { name: 'PenTool', icon: PenTool },
    { name: 'Percent', icon: Percent },
    { name: 'Phone', icon: Phone },
    { name: 'PhoneCall', icon: PhoneCall },
    { name: 'PhoneForwarded', icon: PhoneForwarded },
    { name: 'PhoneIncoming', icon: PhoneIncoming },
    { name: 'PhoneMissed', icon: PhoneMissed },
    { name: 'PhoneOff', icon: PhoneOff },
    { name: 'PhoneOutgoing', icon: PhoneOutgoing },
    { name: 'PieChart', icon: PieChart },
    { name: 'Pin', icon: Pin },
    { name: 'Play', icon: Play },
    { name: 'PlayCircle', icon: PlayCircle },
    { name: 'Plus', icon: Plus },
    { name: 'PlusCircle', icon: PlusCircle },
    { name: 'PlusSquare', icon: PlusSquare },
    { name: 'Podcast', icon: Podcast },
    { name: 'Power', icon: Power },
    { name: 'Printer', icon: Printer },
    { name: 'Puzzle', icon: Puzzle },
    { name: 'QrCode', icon: QrCode },
    { name: 'Radio', icon: Radio },
    { name: 'Receipt', icon: Receipt },
    { name: 'Redo', icon: Redo },
    { name: 'RefreshCcw', icon: RefreshCcw },
    { name: 'RefreshCw', icon: RefreshCw },
    { name: 'Repeat', icon: Repeat },
    { name: 'Rewind', icon: Rewind },
    { name: 'Rocket', icon: Rocket },
    { name: 'RotateCcw', icon: RotateCcw },
    { name: 'RotateCw', icon: RotateCw },
    { name: 'Rss', icon: Rss },
    { name: 'Save', icon: Save },
    { name: 'Scissors', icon: Scissors },
    { name: 'Search', icon: Search },
    { name: 'Send', icon: Send },
    { name: 'Server', icon: Server },
    { name: 'Share', icon: Share },
    { name: 'Shield', icon: Shield },
    { name: 'ShoppingCart', icon: ShoppingCart },
    { name: 'Shuffle', icon: Shuffle },
    { name: 'Sidebar', icon: Sidebar },
    { name: 'Signal', icon: Signal },
    { name: 'SkipBack', icon: SkipBack },
    { name: 'SkipForward', icon: SkipForward },
    { name: 'Slack', icon: Slack },
    
    { name: 'Smartphone', icon: Smartphone },
    { name: 'Snowflake', icon: Snowflake },
   
    { name: 'Speaker', icon: Speaker },
    { name: 'Star', icon: Star },
    { name: 'StopCircle', icon: StopCircle },
    { name: 'Sun', icon: Sun },
    { name: 'Sunrise', icon: Sunrise },
    { name: 'Sunset', icon: Sunset },
    { name: 'Tablet', icon: Tablet },
    { name: 'Tag', icon: Tag },
    { name: 'Target', icon: Target },
    { name: 'Terminal', icon: Terminal },
    { name: 'Thermometer', icon: Thermometer },
  
    { name: 'Timer', icon: Timer },
    { name: 'ToggleLeft', icon: ToggleLeft },
    { name: 'ToggleRight', icon: ToggleRight },
    { name: 'TrendingDown', icon: TrendingDown },
    { name: 'TrendingUp', icon: TrendingUp },
    { name: 'Triangle', icon: Triangle },
    { name: 'Truck', icon: Truck },
    { name: 'Tv', icon: Tv },
    { name: 'Twitch', icon: Twitch },
    { name: 'Twitter', icon: Twitter },
    { name: 'Type', icon: Type },
    { name: 'Underline', icon: Underline },
    { name: 'Undo', icon: Undo },
    { name: 'Unlock', icon: Unlock },
    { name: 'Upload', icon: Upload },
    { name: 'UploadCloud', icon: UploadCloud },
    { name: 'Usb', icon: Usb },
    { name: 'Video', icon: Video },
    { name: 'VideoOff', icon: VideoOff },
    { name: 'Voicemail', icon: Voicemail },
    { name: 'Volume1', icon: Volume1 },
    { name: 'Volume2', icon: Volume2 },
    { name: 'VolumeX', icon: VolumeX },
    { name: 'Watch', icon: Watch },
    { name: 'Webcam', icon: Webcam },
    { name: 'Wifi', icon: Wifi },
    { name: 'WifiOff', icon: WifiOff },
    { name: 'Wind', icon: Wind },
    { name: 'Youtube', icon: Youtube },
    { name: 'Zap', icon: Zap },
    { name: 'ZoomIn', icon: ZoomIn },
    { name: 'ZoomOut', icon: ZoomOut },
    
    // Additional Missing Icons
    { name: 'Menu', icon: Menu },
    { name: 'X', icon: X },
    { name: 'ChevronsDown', icon: ChevronsDown },
    { name: 'ChevronsLeft', icon: ChevronsLeft },
    { name: 'ChevronsRight', icon: ChevronsRight },
    { name: 'ChevronsUp', icon: ChevronsUp },
    { name: 'ChevronsUpDown', icon: ChevronsUpDown },
    { name: 'Rows', icon: Rows },
    { name: 'FolderOpen', icon: FolderOpen },
    { name: 'FolderX', icon: FolderX },
    { name: 'FolderCheck', icon: FolderCheck },
    { name: 'FolderClock', icon: FolderClock },
    { name: 'FolderEdit', icon: FolderEdit },
    { name: 'Files', icon: Files },
    { name: 'FilePlus', icon: FilePlus },
    { name: 'FileMinus', icon: FileMinus },
    { name: 'FileX', icon: FileX },
    { name: 'FileCheck', icon: FileCheck },
    { name: 'FileClock', icon: FileClock },
    { name: 'FileEdit', icon: FileEdit },
    { name: 'FileImage', icon: FileImage },
    { name: 'FileVideo', icon: FileVideo },
    { name: 'FileAudio', icon: FileAudio },
    { name: 'FileSpreadsheet', icon: FileSpreadsheet },
    { name: 'FileCode', icon: FileCode },
    { name: 'Trash', icon: Trash },
    
    { name: 'Share2', icon: Share2 },
    { name: 'Forward', icon: Forward },
    { name: 'Reply', icon: Reply },
    { name: 'ReplyAll', icon: ReplyAll },
    { name: 'Undo2', icon: Undo2 },
    { name: 'Redo2', icon: Redo2 },
    { name: 'CheckCircle2', icon: CheckCircle2 },
    { name: 'CheckSquare2', icon: CheckSquare2 },
    { name: 'XCircle', icon: XCircle },
    { name: 'XSquare', icon: XSquare },

    { name: 'Loader', icon: Loader },
    { name: 'Repeat1', icon: Repeat1 },
    { name: 'MailOpen', icon: MailOpen },
    { name: 'MailPlus', icon: MailPlus },
    { name: 'MailMinus', icon: MailMinus },
    { name: 'MailX', icon: MailX },
    { name: 'MailCheck', icon: MailCheck },
    { name: 'CameraOff', icon: CameraOff },
    { name: 'Volume', icon: Volume },
    { name: 'Music2', icon: Music2 },
    { name: 'Music3', icon: Music3 },
    { name: 'Music4', icon: Music4 },
    { name: 'Disc2', icon: Disc2 },
    { name: 'Disc3', icon: Disc3 },
    { name: 'Images', icon: Images },
    { name: 'Tv2', icon: Tv2 },
    { name: 'MonitorSpeaker', icon: MonitorSpeaker },
    
    { name: 'ShoppingBag', icon: ShoppingBag },
    { name: 'Euro', icon: Euro },
    { name: 'PoundSterling', icon: PoundSterling },
    { name: 'Bitcoin', icon: Bitcoin },
    { name: 'BarChart3', icon: BarChart3 },
    { name: 'BarChart4', icon: BarChart4 },
    { name: 'LineChart', icon: LineChart },
    { name: 'Trophy', icon: Trophy },
    { name: 'Medal', icon: Medal },
    { name: 'Crown', icon: Crown },
    { name: 'CalendarDays', icon: CalendarDays },
    { name: 'CalendarX2', icon: CalendarX2 },
    { name: 'Clock1', icon: Clock1 },
    { name: 'Clock2', icon: Clock2 },
    { name: 'Clock3', icon: Clock3 },
    { name: 'Clock4', icon: Clock4 },
    { name: 'Clock5', icon: Clock5 },
    { name: 'Clock6', icon: Clock6 },
    { name: 'Clock7', icon: Clock7 },
    { name: 'Clock8', icon: Clock8 },
    { name: 'Clock9', icon: Clock9 },
    { name: 'Clock10', icon: Clock10 },
    { name: 'Clock11', icon: Clock11 },
    { name: 'Clock12', icon: Clock12 },
    { name: 'Hourglass', icon: Hourglass },
    { name: 'MoonIcon', icon: MoonIcon },
    { name: 'Stars', icon: Stars },
    { name: 'Globe2', icon: Globe2 },
    { name: 'LocateFixed', icon: LocateFixed },
    { name: 'LocateOff', icon: LocateOff },
    { name: 'Route', icon: Route },
    { name: 'RouteOff', icon: RouteOff },
    { name: 'Milestone', icon: Milestone },
    { name: 'Signpost', icon: Signpost },
    { name: 'SignpostBig', icon: SignpostBig },
    { name: 'Car', icon: Car },
    { name: 'CarFront', icon: CarFront },
    { name: 'CarTaxiFront', icon: CarTaxiFront },
    { name: 'Bus', icon: Bus },
    { name: 'Train', icon: Train },
    { name: 'TrainFront', icon: TrainFront },
    { name: 'Plane', icon: Plane },
    { name: 'PlaneTakeoff', icon: PlaneTakeoff },
    { name: 'PlaneLanding', icon: PlaneLanding },
    { name: 'Ship', icon: Ship },
    { name: 'Anchor', icon: Anchor },
    { name: 'Fuel', icon: Fuel },
    { name: 'ParkingCircle', icon: ParkingCircle },
    { name: 'ParkingSquare', icon: ParkingSquare },
    { name: 'Code2', icon: Code2 },
    { name: 'Cpu', icon: Cpu },
    { name: 'ServerCog', icon: ServerCog },
    { name: 'ServerCrash', icon: ServerCrash },
    { name: 'ServerOff', icon: ServerOff },
    { name: 'BluetoothConnected', icon: BluetoothConnected },
    { name: 'BluetoothOff', icon: BluetoothOff },
    { name: 'Cable', icon: Cable },
    { name: 'Router', icon: Router },
    { name: 'Laptop', icon: Laptop },
    { name: 'MousePointer2', icon: MousePointer2 },
    { name: 'MousePointerClick', icon: MousePointerClick },
    
    { name: 'HeartPulse', icon: HeartPulse },
    { name: 'HeartCrack', icon: HeartCrack },
    { name: 'HeartOff', icon: HeartOff },
    { name: 'Cross', icon: Cross },
    { name: 'CloudHail', icon: CloudHail },
    { name: 'Umbrella', icon: Umbrella },
    { name: 'Rainbow', icon: Rainbow },
    { name: 'Tornado', icon: Tornado },
    { name: 'Waves', icon: Waves },
    { name: 'Mountain', icon: Mountain },
    { name: 'MountainSnow', icon: MountainSnow },
    { name: 'Trees', icon: Trees },
    { name: 'TreePine', icon: TreePine },
    { name: 'TreeDeciduous', icon: TreeDeciduous },
    { name: 'Flower', icon: Flower },
    { name: 'Flower2', icon: Flower2 },
    { name: 'Leaf', icon: Leaf },
    { name: 'UtensilsCrossed', icon: UtensilsCrossed },
    { name: 'Utensils', icon: Utensils },

    { name: 'ChefHat', icon: ChefHat },
    { name: 'Wine', icon: Wine },
    { name: 'Beer', icon: Beer },
    
    { name: 'Tent', icon: Tent },
    { name: 'BedDouble', icon: BedDouble },
    { name: 'BedSingle', icon: BedSingle },
    { name: 'Sofa', icon: Sofa },
    { name: 'Table2', icon: Table2 },
    { name: 'Lamp', icon: Lamp },
    { name: 'LampCeiling', icon: LampCeiling },
    { name: 'LampDesk', icon: LampDesk },
    { name: 'LampFloor', icon: LampFloor },
    { name: 'LampWallDown', icon: LampWallDown },
    { name: 'LampWallUp', icon: LampWallUp },
    { name: 'Bath', icon: Bath },
    { name: 'Refrigerator', icon: Refrigerator },
    { name: 'Microwave', icon: Microwave },
    
    { name: 'Wrench', icon: Wrench },
    { name: 'Drill', icon: Drill },
    { name: 'PaintBucket', icon: PaintBucket },
    { name: 'Paintbrush', icon: Paintbrush },
   
   
    { name: 'School2', icon: School2 },
    { name: 'BookOpen', icon: BookOpen },
    { name: 'Pentagon', icon: Pentagon },
    { name: 'Diamond', icon: Diamond },
    
    { name: 'Power', icon: Power },
    { name: 'Strikethrough', icon: Strikethrough },
    { name: 'ListOrdered', icon: ListOrdered },
    { name: 'ListX', icon: ListX },
    { name: 'Indent', icon: Indent },
    { name: 'Outdent', icon: Outdent },
    { name: 'Quote', icon: Quote },
    { name: 'Heading1', icon: Heading1 },
    { name: 'Heading2', icon: Heading2 },
    { name: 'Heading3', icon: Heading3 },
    { name: 'Heading4', icon: Heading4 },
    { name: 'Heading5', icon: Heading5 },
    { name: 'Heading6', icon: Heading6 },
    { name: 'ArrowBigDown', icon: ArrowBigDown },
    { name: 'ArrowBigLeft', icon: ArrowBigLeft },
    { name: 'ArrowBigRight', icon: ArrowBigRight },
    { name: 'ArrowBigUp', icon: ArrowBigUp },
    { name: 'ArrowBigUpDash', icon: ArrowBigUpDash },
    { name: 'ArrowBigDownDash', icon: ArrowBigDownDash },
    { name: 'ArrowBigLeftDash', icon: ArrowBigLeftDash },
    { name: 'ArrowBigRightDash', icon: ArrowBigRightDash },
    { name: 'CornerDownLeft', icon: CornerDownLeft },
    { name: 'CornerDownRight', icon: CornerDownRight },
    { name: 'CornerLeftDown', icon: CornerLeftDown },
    { name: 'CornerLeftUp', icon: CornerLeftUp },
    { name: 'CornerRightDown', icon: CornerRightDown },
    { name: 'CornerRightUp', icon: CornerRightUp },
    { name: 'CornerUpLeft', icon: CornerUpLeft },
    { name: 'CornerUpRight', icon: CornerUpRight },
    { name: 'BatteryFull', icon: BatteryFull },
    { name: 'BatteryLow', icon: BatteryLow },
    { name: 'SignalHigh', icon: SignalHigh },
    { name: 'SignalLow', icon: SignalLow },
    { name: 'SignalMedium', icon: SignalMedium },
    { name: 'SignalZero', icon: SignalZero },
    { name: 'NfcIcon', icon: NfcIcon },
    { name: 'Barcode', icon: Barcode },
    { name: 'Move3d', icon: Move3d },
    { name: 'MoveHorizontal', icon: MoveHorizontal },
    { name: 'MoveVertical', icon: MoveVertical },
    { name: 'MoveDiagonal', icon: MoveDiagonal },
    { name: 'MoveDiagonal2', icon: MoveDiagonal2 },
    { name: 'Rotate3d', icon: Rotate3d },
    { name: 'FlipHorizontal', icon: FlipHorizontal },
    { name: 'FlipHorizontal2', icon: FlipHorizontal2 },
    { name: 'FlipVertical', icon: FlipVertical },
    { name: 'FlipVertical2', icon: FlipVertical2 },
    { name: 'Layers2', icon: Layers2 },
    { name: 'Layers3', icon: Layers3 },
    { name: 'SearchCheck', icon: SearchCheck },
    { name: 'SearchX', icon: SearchX },
    
    { name: 'Users2', icon: Users2 },
    { name: 'UsersRound', icon: UsersRound },
    { name: 'Contact2', icon: Contact2 },
   
    { name: 'Tags', icon: Tags },
    
    // Missing Icons from Import that weren't in Export

    { name: 'Keyboard', icon: Keyboard },
   
   
    { name: 'WashingMachine', icon: WashingMachine },
    
    { name: 'Magnet', icon: Magnet },
    { name: 'Bed', icon: Bed },
    { name: 'Table', icon: Table },
    { name: 'Volleyball', icon: Volleyball },
    { name: 'Library', icon: Library },
    { name: 'Newspaper', icon: Newspaper },
    { name: 'Telescope', icon: Telescope },
    { name: 'Infinity', icon: Infinity },
    { name: 'Equal', icon: Equal },
    { name: 'Antenna', icon: Antenna },
    { name: 'Focus', icon: Focus },
    { name: 'FilterX', icon: FilterX },
   

    { name: 'Vibrate', icon: Vibrate },
    { name: 'VibrateOff', icon: VibrateOff },
    { name: 'Unplug', icon: Unplug },
    { name: 'CloudSun', icon: CloudSun },
    { name: 'CloudMoon', icon: CloudMoon },
    { name: 'Cloudy', icon: Cloudy },
    { name: 'ScanFace', icon: ScanFace },
    { name: 'Glasses', icon: Glasses },
    { name: 'ContactRound', icon: ContactRound },
    { name: 'Ear', icon: Ear },
    { name: 'EarOff', icon: EarOff },
    { name: 'Footprints', icon: Footprints },
    { name: 'Baby', icon: Baby },
    { name: 'PersonStanding', icon: PersonStanding },
    { name: 'Accessibility', icon: Accessibility },
    { name: 'Dna', icon: Dna },
    { name: 'TestTube', icon: TestTube },
    { name: 'TestTube2', icon: TestTube2 },
    { name: 'Beaker', icon: Beaker },
    { name: 'FlaskConical', icon: FlaskConical },
    { name: 'FlaskConicalOff', icon: FlaskConicalOff },
    { name: 'FlaskRound', icon: FlaskRound },
    { name: 'Atom', icon: Atom },
    { name: 'Orbit', icon: Orbit },
    { name: 'Satellite', icon: Satellite },
    { name: 'Ghost', icon: Ghost },
    { name: 'Skull', icon: Skull },
    { name: 'Biohazard', icon: Biohazard },
    { name: 'Radiation', icon: Radiation },
    { name: 'BugOff', icon: BugOff },
    { name: 'Worm', icon: Worm },
    { name: 'Snail', icon: Snail },
    { name: 'Turtle', icon: Turtle },
    { name: 'Bird', icon: Bird },
    { name: 'Feather', icon: Feather },
    { name: 'Egg', icon: Egg },
    { name: 'EggFried', icon: EggFried },
    { name: 'EggOff', icon: EggOff },
    { name: 'Bone', icon: Bone },
    { name: 'PawPrint', icon: PawPrint },
    { name: 'Milk', icon: Milk },
    { name: 'MilkOff', icon: MilkOff },
    { name: 'Beef', icon: Beef },
    { name: 'Ham', icon: Ham },
    { name: 'Popcorn', icon: Popcorn },
    { name: 'Salad', icon: Salad },
    { name: 'Sandwich', icon: Sandwich },
    { name: 'Soup', icon: Soup },
    { name: 'Pizza', icon: Pizza },
    { name: 'Donut', icon: Donut },
    { name: 'Croissant', icon: Croissant },
    { name: 'Banana', icon: Banana },
    { name: 'Carrot', icon: Carrot },
    { name: 'Fish', icon: Fish },
    { name: 'Rabbit', icon: Rabbit },
    { name: 'Dog', icon: Dog },
    { name: 'Cat', icon: Cat },
    { name: 'Coffee', icon: Coffee },
    { name: 'IceCream', icon: IceCream },
    { name: 'IceCream2', icon: IceCream2 },
    { name: 'Cookie', icon: Cookie },
    { name: 'Apple', icon: Apple },
    { name: 'Cherry', icon: Cherry },
    { name: 'Grape', icon: Grape },
    { name: 'Warehouse', icon: Warehouse },
    { name: 'Scissors', icon: Scissors },
    { name: 'Ruler', icon: Ruler },
    { name: 'Pencil', icon: Pencil },
    { name: 'Pen', icon: Pen },
    { name: 'Eraser', icon: Eraser },
    { name: 'Pin', icon: Pin },
    { name: 'Vault', icon: Vault },
    { name: 'Dumbbell', icon: Dumbbell },
    { name: 'Weight', icon: Weight },
    { name: 'GraduationCap', icon: GraduationCap },
    { name: 'School', icon: School },
    { name: 'Brain', icon: Brain },
    { name: 'Microscope', icon: Microscope },
    { name: 'Asterisk', icon: Asterisk },
    { name: 'Copyright', icon: Copyright },

    { name: 'Bolt', icon: Bolt },
    { name: 'SunDim', icon: SunDim },
    { name: 'SunMedium', icon: SunMedium },
    { name: 'SunMoon', icon: SunMoon },
    { name: 'SunSnow', icon: SunSnow },
    { name: 'LifeBuoy', icon: LifeBuoy },
    { name: 'ShieldOff', icon: ShieldOff },
    { name: 'LockKeyhole', icon: LockKeyhole },
    { name: 'Fingerprint', icon: Fingerprint }
  ];
